/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import bulkEditor from "strapi-plugin-bulk-editor/strapi-admin";
import schemaVisualizer from "strapi-plugin-schema-visualizer/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "bulk-editor": bulkEditor,
    "schema-visualizer": schemaVisualizer,
  },
});
